# Application properties for Spring Boot Best Practices
application.name=SBBP
application.environment=dev

spring.application.name=SPBP
# enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# allow remote access to the console (optional)
spring.h2.console.settings.web-allow-others=false

# simple in-memory datasource (optional)
spring.datasource.url=jdbc:h2:mem:xperia-spbp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=